from typing import Protocol


class ExtensionRegistry(Protocol):
    """Trusted server-side extension contract. No dynamic installation in stage 1."""
    def register_model_provider(self, name: str, factory: object) -> None: ...
    def register_sandbox_provider(self, name: str, factory: object) -> None: ...
    def register_notification_channel(self, name: str, factory: object) -> None: ...


class NotificationChannel(Protocol):
    async def send(self, subject: str, body: str, idempotency_key: str) -> None: ...
