[CmdletBinding()] param([Parameter(Mandatory)][string]$Backup,[string]$InstallDirectory='',[switch]$Force)
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest; . (Join-Path $PSScriptRoot 'Common.ps1')
if(-not $Force){Stop-WithError 'Restore replaces current data and secrets. Review the backup, then rerun with -Force.'}; if(-not $InstallDirectory){$InstallDirectory=Get-DefaultInstallRoot}; $InstallDirectory=[IO.Path]::GetFullPath($InstallDirectory); $Backup=[IO.Path]::GetFullPath($Backup)
$manifest=$Backup -replace '\.zip$','.manifest.json'; if(-not(Test-Path $manifest)){Stop-WithError 'Backup manifest is missing'}; $meta=Get-Content -Raw $manifest|ConvertFrom-Json; if((Get-FileHash -Algorithm SHA256 $Backup).Hash.ToLowerInvariant() -ne $meta.sha256){Stop-WithError 'Backup checksum verification failed'}
Assert-Docker; $versionDirectory=Get-CurrentVersionDirectory $InstallDirectory; Invoke-Compose $InstallDirectory $versionDirectory @('down')
$stage=Join-Path $InstallDirectory '.restore-staging'; if(Test-Path $stage){Stop-WithError 'Restore staging path already exists'}; Expand-Archive -LiteralPath $Backup -DestinationPath $stage
try { if(-not(Test-Path (Join-Path $stage '.env')) -or -not(Test-Path (Join-Path $stage 'data'))){Stop-WithError 'Backup content is incomplete'}; $data=[IO.Path]::GetFullPath((Get-EnvValue (Join-Path $InstallDirectory '.env') 'MAINTAINER_DATA_DIR')); if($data -eq [IO.Path]::GetPathRoot($data)){Stop-WithError 'Refusing to replace a filesystem root'}; if(Test-Path $data){Remove-Item -LiteralPath $data -Recurse -Force}; Move-Item (Join-Path $stage 'data') $data; Move-Item -Force (Join-Path $stage '.env') (Join-Path $InstallDirectory '.env'); Protect-PrivateFile (Join-Path $InstallDirectory '.env') }
finally { if(Test-Path $stage){Remove-Item -LiteralPath $stage -Recurse -Force} }
Invoke-Compose $InstallDirectory $versionDirectory @('up','-d','--wait','--wait-timeout','120'); Wait-MaintainerHealth ([int](Get-EnvValue (Join-Path $InstallDirectory '.env') 'MAINTAINER_PORT')) | Out-Null; Write-Host 'Restore completed and health check passed.'
